import ToastProvider from "@components/Providers/ToastProvider";
import "@styles/globals.css";
import 'bootstrap-icons/font/bootstrap-icons.css';
import type { Metadata } from 'next'
import SessionProvider from "@components/Providers/UserProvider";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100 dark:bg-zinc-900">
        <ToastProvider>
          <SessionProvider>
            {children}
          </SessionProvider>
        </ToastProvider>
      </body>
    </html>
  )
}