import Navbar from "@components/Navbar/Navbar";
import Provider from "@components/Provider";
import "@styles/globals.css";
import 'bootstrap-icons/font/bootstrap-icons.css';
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <Provider>
          <Navbar />
          <div className="container mx-auto pt-12">
            {children}
          </div>
        </Provider>
      </body>
    </html>
  )
}
